spring.application.name=rica-api

# PostgreSQL - investigadores
spring.datasource.url=jdbc:postgresql://localhost:5432/rica
spring.datasource.username=rica
spring.datasource.password=rica
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# MongoDB - publicaciones
spring.data.mongodb.uri=mongodb://localhost:27017/rica
